### ISSUE TITLE
Make backwards compatible with oXygen 16

### ISSUE THREAD

**Issue by nakohdo** [mgcalo/model2dita#48]
I've already moved the Author action to the framework and changed the CSS accordingly:

``` CSS
model:after{
    margin-top:1em;
    padding-top:1em;
    display:block;
    border-top:1px solid silver;
      content: oxy_button(actionID, "model2dita_generate")
}
```

However, I get a Java error because the .jar file is compiled with a newer version than that of oXygen 16:

```
[ AWT-EventQueue-0 ]  
-  java.lang.UnsupportedClassVersionError: org/thinkdita/model2dita/GenerateOperation : 
Unsupported major.minor version 52.0
```

It would be great if you could provide an oXygen-16-compatible version.
